import pandas as pd

# Load the CSV generated by the previous script
df = pd.read_csv("todo3_comparison.csv")

# Ensure columns are numeric (ignoring errors for the 'Benchmark' column or 'ERR' strings)
for col in df.columns[1:]:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Drop any rows where ABC failed and returned 'ERR' (NaN after to_numeric)
df = df.dropna()

# 1. Calculate the analytical metrics (ML vs High-Effort)
df['Area_Overhead_%'] = ((df['ML_Guided_Area'] - df['High_Effort_C8_Area']) / df['High_Effort_C8_Area']) * 100
df['Delay_Overhead_%'] = ((df['ML_Guided_Delay'] - df['High_Effort_C8_Delay']) / df['High_Effort_C8_Delay']) * 100
df['Speedup_X'] = df['High_Effort_C8_Time'] / df['ML_Guided_Time']

# 2. Format the data for display
report_df = pd.DataFrame()
report_df['Benchmark'] = df['Benchmark']

# Format the raw metrics into "Area / Delay / Time" strings
report_df['High-Effort (C=8)'] = df.apply(lambda row: f"{int(row['High_Effort_C8_Area'])} / {int(row['High_Effort_C8_Delay'])} / {row['High_Effort_C8_Time']:.2f}s", axis=1)
report_df['Low-Effort (C=2)'] = df.apply(lambda row: f"{int(row['Low_Effort_C2_Area'])} / {int(row['Low_Effort_C2_Delay'])} / {row['Low_Effort_C2_Time']:.2f}s", axis=1)
report_df['ML-Guided (C=8)'] = df.apply(lambda row: f"{int(row['ML_Guided_Area'])} / {int(row['ML_Guided_Delay'])} / {row['ML_Guided_Time']:.2f}s", axis=1)

# Add the final comparison columns with dynamic signs (+ for positive, - for negative)
report_df['Area Overhead'] = df['Area_Overhead_%'].apply(lambda x: f"{x:+.1f}%")
report_df['Delay Overhead'] = df['Delay_Overhead_%'].apply(lambda x: f"{x:+.1f}%")
report_df['Speedup'] = df['Speedup_X'].apply(lambda x: f"{x:.2f}x")

# Print the beautifully formatted table to the terminal
print("\n--- Final Quality of Results (QoR) Comparison ---")
print("Format: Area (nd) / Delay (lev) / Time (s)\n")
print(report_df.to_markdown(index=False))

# Optional: Print the average improvement
avg_area_overhead = df['Area_Overhead_%'].mean()
avg_delay_overhead = df['Delay_Overhead_%'].mean()
avg_speedup = df['Speedup_X'].mean()

print("\n--- Summary ---")
print(f"Average Area Overhead vs High-Effort:  {avg_area_overhead:+.2f}%")
print(f"Average Delay Overhead vs High-Effort: {avg_delay_overhead:+.2f}%")
print(f"Average Speedup vs High-Effort:        {avg_speedup:.2f}x")